=== codonlearning/system-notifications/notification-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "number"
      },
      "notificationStart": {
        "type": "string"
      },
      "notificationEnd": {
        "type": "string"
      },
      "downtimeStart": {
        "type": "string"
      },
      "downtimeDuration": {
        "type": "object",
        "properties": {
          "minutes": {
            "type": "number"
          }
        },
        "required": [
          "minutes"
        ]
      },
      "message": {
        "type": "string"
      },
      "showToRoles": {
        "type": "array",
        "items": {}
      }
    },
    "required": [
      "id",
      "notificationStart",
      "notificationEnd",
      "message"
    ]
  }
}

=== codonlearning/system-notifications/notifications.json
[
  {
    "id": 1,
    "notificationStart": "2024-11-06T12:00:00-04:00",
    "notificationEnd": "2024-11-06T18:20:00-04:00",
    "downtimeStart": "2024-11-06T14:10:00-04:00",
    "downtimeDuration": {
      "minutes": 20
    },
    "message": "Test Notification 1",
    "showToRoles": []
  },
  {
    "id": 2,
    "notificationStart": "2024-11-07T12:00:00-04:00",
    "notificationEnd": "2024-11-07T18:20:00-04:00",
    "downtimeStart": "2024-11-07T14:10:00-04:00",
    "downtimeDuration": {
      "minutes": 20
    },
    "message": "Notification 2",
    "showToRoles": []
  },
  {
    "id": 3,
    "notificationStart": "2024-11-07T12:00:00-04:00",
    "notificationEnd": "2024-11-07T18:20:00-04:00",
    "message": "Notification 3 - no downtime, just a notification message"
  },
  {
    "id": 4,
    "notificationStart": "2024-11-07T16:00:00-04:00",
    "notificationEnd": "2024-11-07T20:20:00-04:00",
    "downtimeStart": "2024-11-07T18:10:00-04:00",
    "downtimeDuration": {
      "minutes": 20
    },
    "message": "Notification 4",
    "showToRoles": []
  },
  {
    "id": 5,
    "notificationStart": "2024-11-08T14:00:00-05:00",
    "notificationEnd": "2024-11-12T23:59:59-05:00",
    "downtimeStart": "2024-11-12T00:00:00-05:00",
    "downtimeDuration": {
      "minutes": 5
    },
    "message": "Notification 5",
    "showToRoles": []
  }
]
